# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./version.hpp \
    ./CV_test_GUI.h \
    ./include/Filler.hpp
SOURCES += ./CV_test_GUI.cpp \
    ./main.cpp \
    ./include/Filler.cpp
FORMS += ./CV_test_GUI.ui
RESOURCES += CV_test_GUI.qrc
